# Generated by Django 6.1.1 on 2026-09-25 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(db_index=True, default='worktree', help_text='Branch or worktree label the scanner was pointed at', max_length=64)),
                ('trigger', models.CharField(default='cli', help_text='What started the scan: cli / api / test', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.SmallIntegerField(blank=True, help_text='0 = clean, 1 = critical findings', null=True)),
                ('findings_total', models.PositiveIntegerField(default=0, help_text='Number of findings stored for this run')),
                ('rules_run', models.CharField(blank=True, default='', help_text='Comma list of rule ids', max_length=256)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(db_index=True, help_text='Registry key from security.weights (e.g. raw_sql)', max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', max_length=16)),
                ('file_path', models.CharField(blank=True, default='', help_text='Location relative to backend/ (empty for runtime probes)', max_length=512)),
                ('line_no', models.PositiveIntegerField(blank=True, help_text='1-based source line, when the evidence is textual', null=True)),
                ('message', models.TextField(help_text='One-line evidence summary')),
                ('fingerprint', models.CharField(db_index=True, help_text='sha256(rule|file|line) -- idempotent UPSERT key per scan', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_run', models.ForeignKey(help_text='Scan execution that observed this finding', on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='security.scanrun')),
            ],
            options={
                'ordering': ['rule_id', 'file_path', 'line_no'],
                'constraints': [models.UniqueConstraint(fields=('scan_run', 'fingerprint'), name='uniq_finding_per_scan')],
            },
        ),
    ]
